### ISSUE TITLE
Example is broken on premise 2.1.1

### ISSUE THREAD

**Issue by marc-vdm** [premise-community-scenarios/hydrogen-prospective-scenarios#2]
When following the [example](https://github.com/premise-community-scenarios/hydrogen-prospective-scenarios?tab=readme-ov-file#how-to-use-it), I get the following error on Premise 2.1.1:

```python
/home/marc/.conda/envs/premise/bin/python /home/marc/sd/framework_pycharm/premise/premise_testing.py 
ERROR 1: PROJ: proj_create_from_database: Open of /home/marc/.conda/envs/premise/share/proj failed
Traceback (most recent call last):
  File "/home/marc/sd/framework_pycharm/premise/premise_testing.py", line 28, in <module>
    ndb = NewDatabase(
          ^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/new_database.py", line 551, in __init__
    self.scenarios = [check_scenarios(scenario, key) for scenario in scenarios]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/new_database.py", line 551, in <listcomp>
    self.scenarios = [check_scenarios(scenario, key) for scenario in scenarios]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/new_database.py", line 404, in check_scenarios
    scenario["external scenarios"] = check_external_scenarios(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/external_data_validation.py", line 950, in check_external_scenarios
    external_scenario["data"] = check_scenario_data_file(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/external_data_validation.py", line 811, in check_scenario_data_file
    scenario_data = resource.read()
                    ^^^^^^^^^^^^^^^
  File "/home/marc/.conda/envs/premise/lib/python3.11/site-packages/datapackage/resource.py", line 383, in read
    return self.__get_table().read(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/.conda/envs/premise/lib/python3.11/site-packages/tableschema/table.py", line 353, in read
    for count, row in enumerate(rows, start=1):
  File "/home/marc/.conda/envs/premise/lib/python3.11/site-packages/tableschema/table.py", line 215, in iter
    for row_number, headers, row in iterator:
  File "/home/marc/.conda/envs/premise/lib/python3.11/site-packages/tableschema/table.py", line 508, in builtin_processor
    row = self.__schema.cast_row(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/.conda/envs/premise/lib/python3.11/site-packages/tableschema/schema.py", line 275, in cast_row
    exc_handler(exc, row_number=row_number, row_data=keyed_row,
  File "/home/marc/.conda/envs/premise/lib/python3.11/site-packages/tableschema/helpers.py", line 90, in default_exc_handler
    raise exc
datapackage.exceptions.CastError: Row length 13 doesn't match fields count 11 for row "2"
```

**Comment by romainsacchi** [comment]
I do not have this issue. It seems it sees 11 values in row 2, while it should be reading 13.

**Comment by romainsacchi** [comment]
Could it be due to the regional settings of the computer and the assumed separating value?

**Comment by romainsacchi** [comment]
I mean I see nothing wrong with the file...

<img width="812" alt="Screenshot 2024-09-09 at 16 23 32" src="https://github.com/user-attachments/assets/cf5adb41-efdb-43a7-8751-0efcf65ee2f6">

**Comment by marc-vdm** [comment]
I'm not sure what the problem is here, when I edit the error message in `tableschema` to include the row and header fields, the header seems to be missing `model` and `pathway`: 

`datapackage.exceptions.CastError: Row length 13 doesn't match fields count 11 >>>['remind', 'SSP2-NDC', 'Business as usual', 'CHA', 'Efficiency|AE|Stack|Steel', '-', '0.1', '0.12', '0.14', '0.16', '0.18', '0.21', '0.25']<<< >>>['scenario', 'region', 'variables', 'unit', '2020', '2025', '2030', '2035', '2040', '2045', '2050']<<< for row "2"`

For reference: I edited line 255-257 of `tableschema/schema.py` to:
`message = (
                'Row length %s doesn\'t match fields count %s >>>%s<<< >>>%s<<<' +
                row_number_info) % (len(row), len(self.fields), row, [f.name for f in self.fields])`


I wouldn't know at all why or how this could happen. From my understanding of the traceback, this happens during the reading of the file by `datapackage`.

Here's my full environment in case it's useful:

```shell
(premise) marc@framework7640u:~$ conda list
# packages in environment at /home/marc/.conda/envs/premise:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asteval                   1.0.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.7.22              hbd3ac97_10    conda-forge
aws-c-cal                 0.7.1                h87b94db_1    conda-forge
aws-c-common              0.9.23               h4ab18f5_0    conda-forge
aws-c-compression         0.2.18               he027950_7    conda-forge
aws-c-event-stream        0.4.2               h7671281_15    conda-forge
aws-c-http                0.8.2                he17ee6b_6    conda-forge
aws-c-io                  0.14.10              h826b7d6_1    conda-forge
aws-c-mqtt                0.10.4               hcd6a914_8    conda-forge
aws-c-s3                  0.6.0                h365ddd8_2    conda-forge
aws-c-sdkutils            0.1.16               he027950_3    conda-forge
aws-checksums             0.1.18               he027950_7    conda-forge
aws-crt-cpp               0.27.3               hda66527_2    conda-forge
aws-sdk-cpp               1.11.329             h46c3b66_9    conda-forge
azure-core-cpp            1.12.0               h830ed8b_0    conda-forge
azure-identity-cpp        1.8.0                hdb0d106_1    conda-forge
azure-storage-blobs-cpp   12.11.0              ha67cba7_1    conda-forge
azure-storage-common-cpp  12.6.0               he3f277c_1    conda-forge
azure-storage-files-datalake-cpp 12.10.0              h29b5301_1    conda-forge
blas                      1.0                    openblas  
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
boto3                     1.34.144           pyhd8ed1ab_0    conda-forge
botocore                  1.34.144        pyge310_1234567_0    conda-forge
bottleneck                1.4.0           py311h18e1886_1    conda-forge
brightway2                2.4.6              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
brotlicffi                1.1.0.0         py311hb755f60_1    conda-forge
bw2analyzer               0.10               pyhd8ed1ab_0    conda-forge
bw2calc                   1.8.2           py311h38be061_0    conda-forge
bw2data                   3.6.6              pyhd8ed1ab_0    conda-forge
bw2io                     0.8.12             pyhd8ed1ab_0    conda-forge
bw2parameters             1.1.0              pyhd8ed1ab_0    conda-forge
bw_migrations             0.2                pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.32.2               h4bc722e_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
cchardet                  2.1.7           py311hb755f60_5    conda-forge
certifi                   2024.8.30       py311h06a4308_0  
cffi                      1.16.0          py311hb3a22ac_0    conda-forge
cfitsio                   4.4.1                hf8ad068_0    conda-forge
chardet                   5.2.0           py311h38be061_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
constructive_geometries   0.9.5              pyhd8ed1ab_0    conda-forge
contextlib2               21.6.0             pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py311h9547e67_0    conda-forge
country_converter         1.2                pyhd8ed1ab_0    conda-forge
cryptography              42.0.8          py311h4a61cc7_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dataflows-tabulator       1.54.3             pyhd8ed1ab_0    conda-forge
datapackage               1.15.2             pyh44b312d_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
ecoinvent_interface       2.4.1              pyhd8ed1ab_0    conda-forge
eight                     1.0.1              pyhd8ed1ab_4    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fiona                     1.9.6           py311h9718c99_3    conda-forge
flask                     3.0.3              pyhd8ed1ab_0    conda-forge
flexcache                 0.3                pyhd8ed1ab_0    conda-forge
flexparser                0.3.1              pyhd8ed1ab_0    conda-forge
fmt                       10.2.1               h00ab1b0_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py311h61187de_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    2.0.0                h743c826_0    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
gdal                      3.9.1           py311h4a2bcd2_7    conda-forge
geos                      3.12.2               hac33072_0    conda-forge
geotiff                   1.7.3                hf7fa9e8_1    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glog                      0.7.1                hbabe93e_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
greenlet                  3.0.3           py311hb755f60_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
ijson                     3.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_metadata        8.0.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
inflate64                 1.0.0           py311h459d7ec_1    conda-forge
intel-openmp              2022.0.1          h06a4308_3633  
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
itsdangerous              2.2.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
json-c                    0.17                 h1220068_1    conda-forge
jsonlines                 4.0.0              pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py311h38be061_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
kealib                    1.5.3                hee9dde6_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py311h9547e67_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_he02047a_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libarrow                  16.1.0          h34456a7_14_cpu    conda-forge
libarrow-acero            16.1.0          he02047a_14_cpu    conda-forge
libarrow-dataset          16.1.0          he02047a_14_cpu    conda-forge
libarrow-substrait        16.1.0          hc9a23c6_14_cpu    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.8.0                hca28451_1    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgdal                   3.9.1                ha770c72_7    conda-forge
libgdal-core              3.9.1                h1d1841c_7    conda-forge
libgdal-fits              3.9.1                hdd6600c_7    conda-forge
libgdal-grib              3.9.1                h5f34788_7    conda-forge
libgdal-hdf4              3.9.1                ha39a594_7    conda-forge
libgdal-hdf5              3.9.1                ha2ed5f0_7    conda-forge
libgdal-jp2openjpeg       3.9.1                h2ebfdf0_7    conda-forge
libgdal-kea               3.9.1                h2b45729_7    conda-forge
libgdal-netcdf            3.9.1                h94e7027_7    conda-forge
libgdal-pdf               3.9.1                h562c687_7    conda-forge
libgdal-pg                3.9.1                he047751_7    conda-forge
libgdal-postgisraster     3.9.1                he047751_7    conda-forge
libgdal-tiledb            3.9.1                hfcb00c0_7    conda-forge
libgdal-xls               3.9.1                h062f1c4_7    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.80.3               h8a4344b_1    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libgoogle-cloud           2.26.0               h26d7fe4_0    conda-forge
libgoogle-cloud-storage   2.26.0               ha262f82_0    conda-forge
libgrpc                   1.62.2               h15f2491_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libkml                    1.3.0             hbbc8833_1020    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnetcdf                 4.9.2           nompi_h135f659_114    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libparquet                16.1.0          h9e5060d_14_cpu    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     16.3                 ha72fbe1_0    conda-forge
libprotobuf               4.25.3               h08a7969_0    conda-forge
libre2-11                 2023.09.01           h5a48ba9_2    conda-forge
librttopo                 1.1.0               hc670b87_16    conda-forge
libspatialite             5.1.0                h15fa968_8    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libthrift                 0.19.0               hb90f79a_1    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
linear-tsv                1.1.0                      py_1    conda-forge
llvmlite                  0.43.0          py311hbde99c3_0    conda-forge
lxml                      4.9.3           py311h1a07684_3    conda-forge
lxmlh                     1.3.3              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
markupsafe                2.1.5           py311h459d7ec_0    conda-forge
matplotlib-base           3.9.1           py311hffb96ce_0    conda-forge
minizip                   4.0.7                h401b404_0    conda-forge
mkl                       2022.1.0           hc2b9512_224  
mrio_common_metadata      0.2.1              pyhd8ed1ab_0    conda-forge
multivolumefile           0.2.3              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.102                h593d115_0    conda-forge
numba                     0.60.0          py311h4bc866e_0    conda-forge
numpy                     1.26.4          py311h24aa872_0  
numpy-base                1.26.4          py311hbfb1bba_0  
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openpyxl                  3.1.4           py311h459d7ec_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
orc                       2.0.1                h17fec99_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py311h14de704_1    conda-forge
pcre2                     10.44                h0f59acf_0    conda-forge
peewee                    3.17.6          py311h26bb8ec_0    conda-forge
pillow                    10.4.0          py311h82a398c_0    conda-forge
pint                      0.24.3             pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
poppler                   24.07.0              hb0d391f_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.3                 h8e811e2_0    conda-forge
premise                   2.1.1              pyhd8ed1ab_0    conda-forge
premise_gwp               0.9.6              pyhd8ed1ab_0    conda-forge
prettytable               3.10.2             pyhd8ed1ab_0    conda-forge
proj                      9.4.1                hb784bbd_0    conda-forge
psutil                    6.0.0           py311h331c9d8_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py7zr                     0.21.1             pyhd8ed1ab_0    conda-forge
pyarrow                   16.1.0          py311hbd00459_4    conda-forge
pyarrow-core              16.1.0          py311h8c3dac4_4_cpu    conda-forge
pybcj                     1.0.2           py311h459d7ec_0    conda-forge
pycasreg                  0.1.0              pyhd8ed1ab_0    conda-forge
pycountry                 24.6.1             pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pycryptodomex             3.20.0          py311h61187de_0    conda-forge
pydantic                  2.8.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.20.1          py311hb3a8bbb_0    conda-forge
pydantic-settings         2.3.4              pyhd8ed1ab_0    conda-forge
pyecospold                3.5.3              pyhd8ed1ab_0    conda-forge
pypardiso                 0.4.6              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyppmd                    1.1.0           py311hb755f60_0    conda-forge
pyprind                   2.11.2          py311h38be061_1005    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.9          hb806964_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-dotenv             1.0.1              pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyxlsb                    1.0.10             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
pyzstd                    0.16.0          py311hb6f056b_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
re2                       2023.09.01           h7f4b329_2    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3986                   2.0.0              pyhd8ed1ab_0    conda-forge
rpds-py                   0.19.0          py311hb3a8bbb_0    conda-forge
s2n                       1.4.17               he19d79f_0    conda-forge
s3transfer                0.10.2             pyhd8ed1ab_0    conda-forge
schema                    0.7.7              pyhd8ed1ab_0    conda-forge
scipy                     1.14.0          py311h517d4fd_1    conda-forge
setuptools                70.3.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.1.0              pyhd8ed1ab_0    conda-forge
shapely                   2.0.5           py311h5925939_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
sparse                    0.15.4             pyhd8ed1ab_0    conda-forge
spdlog                    1.13.0               hd2e6256_0    conda-forge
sqlalchemy                2.0.31          py311h331c9d8_0    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
stats_arrays              0.6.6              pyhd8ed1ab_0    conda-forge
tableschema               1.20.11            pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tabulator                 1.53.5             pyhd8ed1ab_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
tiledb                    2.24.2               hc55ee95_2    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzcode                    2024a                h3f72095_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
unfold                    1.2.0              pyhd8ed1ab_0    conda-forge
unicodecsv                0.14.1             pyhd8ed1ab_2    conda-forge
unidecode                 1.3.8              pyhd8ed1ab_0    conda-forge
uriparser                 0.9.8                hac33072_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
voluptuous                0.15.2             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
werkzeug                  3.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
whoosh                    2.7.4           py311h38be061_8    conda-forge
wrapt                     1.16.0          py311h459d7ec_0    conda-forge
wurst                     0.4                pyhd8ed1ab_0    conda-forge
xarray                    2024.6.0           pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.5                h666cd97_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.1.9              pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipfile-deflate64         0.2.0           py311h459d7ec_4    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h4ab18f5_1    conda-forge
zstandard                 0.23.0          py311h5cd10c7_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by marc-vdm** [comment]
Update: I see that `model` and `pathway` are not included in the schema fields here
https://github.com/premise-community-scenarios/hydrogen-prospective-scenarios/blob/d8bfe47c210990f85b11dd9fe744cdc38033f849/datapackage.json#L43-L49

Perhaps that could be the cause of the issue, though I do not know why it would work for you and not for me if that were the case.

**Comment by romainsacchi** [comment]
Right, that is it. These two columns should not be in the scenario_data file. I’ll fix that tomorrow.

**Comment by marc-vdm** [comment]
Alright thanks!

**Comment by romainsacchi** [comment]
OK the reason it was working on my end was because I was not running the same stuff :-)

**Comment by romainsacchi** [comment]
OK, it should be fixed now.

**Comment by marc-vdm** [comment]
Yes this specific issue is resolved
