### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by marc-vdm** [premise-community-scenarios/hydrogen-prospective-scenarios#3]
Sorry to be keeping you busy.

When running the example (in readme), I get the following traceback:
```python
Traceback (most recent call last):
  File "/home/marc/sd/framework_pycharm/premise/premise_testing.py", line 51, in <module>
    ndb.update("external")
  File "/home/marc/sd/framework_pycharm/premise/premise/new_database.py", line 972, in update
    scenario = update_func(scenario, *fixed_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/external.py", line 75, in _update_external_scenarios
    additional = AdditionalInventory(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/inventory_imports.py", line 992, in __init__
    super().__init__(database, version_in, version_out, path, system_model)
  File "/home/marc/sd/framework_pycharm/premise/premise/inventory_imports.py", line 378, in __init__
    self.import_db = self.load_inventory()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marc/sd/framework_pycharm/premise/premise/inventory_imports.py", line 1017, in load_inventory
    self.download_file(path_str, TEMP_CSV_FILE)
  File "/home/marc/sd/framework_pycharm/premise/premise/inventory_imports.py", line 1007, in download_file
    writer.writerow(line.decode("utf-8").split(","))
                    ^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte

```

**Comment by romainsacchi** [comment]
Strange, it works for me. OK, I've cleaned the CSV containing the LCIs and saved it again with UTF-8 encoding. Can you tell me whether it works now?

**Comment by marc-vdm** [comment]
Nope, same error :/

**Comment by romainsacchi** [comment]
Alright. I think a not ideal solution would be to download the data package and open and save the scenario_data.csv file with a utf-8 encoding and try again. I don't see other obvious solutions, sorry. And I have no explanations as to why it does not work for you. Maybe a Windows vs Mac thing?

**Comment by marc-vdm** [comment]
Alright thanks for the info at least! 

Do I just replace `fp = r"https://raw.githubusercontent.com/premise-community-scenarios/hydrogen-prospective-scenarios/main/datapackage.json"` with the same file structure locally?

**Comment by romainsacchi** [comment]
No, you'd need to download the reop as a zip file and point to the zip file directly.

**Comment by marc-vdm** [comment]
I think I found the problem.

After downloading the datapackage and running it locally, this works fine now, using the github link still fails, If I understand correctly, data is cached right? Would there be a way to automatically invalidate cached files, e.g. by comparing hashes?
